# Generated by Django 5.2 on 2025-07-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiante')),
            ],
        ),
    ]
