# Generated by Django 5.2 on 2025-07-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='tipo',
            field=models.CharField(choices=[('Emocional', 'Emocional'), ('Conductual', 'Conductual'), ('Aprendizaje', 'Aprendizaje'), ('Familiar', 'Familiar'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
