# Generated by Django 5.2 on 2025-07-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docentes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
