# Generated by Django 5.2 on 2025-07-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateField()),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En seguimiento', 'En seguimiento'), ('Cerrado', 'Cerrado')], max_length=20)),
                ('motivo', models.CharField(choices=[('Emocional', 'Emocional'), ('Aprendizaje', 'Aprendizaje')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiante')),
            ],
        ),
    ]
